### ISSUE TITLE
Default deploymentName

### ISSUE THREAD

**Issue by kmagusiak** [Azure/arm-deploy#103]
The default `deploymentName` seems to be the base name of the template file. Could it be set to the repository name with a timestamp?

In Azure DevOps, date and random chars are added so that two deployments in the same resource group don't collide.
Here's an example where the last deployment was done using github:
![image](https://user-images.githubusercontent.com/1943198/172357365-8732074c-3574-4efd-984b-87c30e553a55.png)

**Comment by t-dedah** [comment]
Hi @kmagusiak Thats a good suggestion, I will discuss this with the team and get back to you.

**Comment by t-dedah** [comment]
Hi @kmagusiak As `deploymentName` is already an input, you can use that to group to create separate deployments. If you want each workflow run to generate a new deployment with a new name then trying adding some sort of automatic variation like using run number. `${{github.run_number}}`

We are closing this issue now but feel free to reopen if more information is needed.

**Comment by kmagusiak** [comment]
> Hi @kmagusiak As `deploymentName` is already an input, you can use that to group to create separate deployments. If you want each workflow run to generate a new deployment with a new name then trying adding some sort of automatic variation like using run number. `${{github.run_number}}`
> 
> We are closing this issue now but feel free to reopen if more information is needed.

Hello,

This is what I've set today (not exactly run_number, but similar). The issue was to change the default behavior and use something unique.

Best regards,
Krzysztof
