### ISSUE TITLE
Deploy Bicep without Resourcegroup defined in the GitHub Actions Workflow

### ISSUE THREAD

**Issue by aavdberg** [Azure/arm-deploy#110]
Having the following problem with using the Azure/arm-deploy@v1 action, namely how can I deploy without specifying a resourcegroup .

![image](https://user-images.githubusercontent.com/22030609/185395366-6f66ae40-eb31-43b3-a45b-94545e35a8cb.png)

**Comment by t-dedah** [comment]
Hi @aavdberg as the scope is `managementgroup`, we dont have to specify `resourceGroupName` which is also mentioned [here](https://github.com/Azure/arm-deploy#inputs). May I know the problem you are facing while running the workflow?

**Comment by aavdberg** [comment]
I had to add the following:
```
managementGroupId: ${{ secrets.AZURE_ALZITEU_MANAGEMENTGROUP_ID }}
```
and then it worked
