### ISSUE TITLE
Warning in workflow about nodejs version

### ISSUE THREAD

**Issue by johan-lindqvist** [Azure/arm-deploy#114]
It seems that GitHub is deprecating nodejs12 which gives warnings when using this action in a workflow:
![image](https://user-images.githubusercontent.com/1523775/195315569-2640c056-eca6-40f6-9ee2-4e352603eb52.png)

Warning in text: 
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/arm-deploy, azure/functions-action
```

**Comment by t-dedah** [comment]
Thank you @johan-lindqvist for the heads-up, we will be pushing this fix in the coming days.

**Comment by t-dedah** [comment]
Hi @johan-lindqvist @oxbo-andre we have released a new version so this should work fine now. Let me know if you are still facing this issue.

**Comment by johan-lindqvist** [comment]
Tested just now, no more warnings 👍
