### ISSUE TITLE
`set-output` deprecation warning from GitHub actions

### ISSUE THREAD

**Issue by AshleyRoll** [Azure/arm-deploy#115]
Similar to #114 GitHub is also warning about deprecating the use of the `set-output` command. 

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Their solution for action authors is to bump `@actions/core` to `v1.10.0` or greater. 

I note there is a PR from dependabot #111 to bump to `1.91`, but that will not fix this issue.

**Comment by t-dedah** [comment]
Thank you @AshleyRoll for the heads-up, we will update this action to use the latest @actions/core soon.

**Comment by adrianmo** [comment]
@t-dedah thanks for the awesome work you are doing with this action. 

I just wanted to ask you if you could release a new version of the action that includes your recent update to use the latest version of `actions/core` (`v1.10.0`). 

We've been seeing very strange behaviors with output parsing that seemed to be resolved in your `main` branch. But we don't feel very comfortable with pinning our actions to a `main` branch.

Thank you!

**Comment by adrianmo** [comment]
This is what I was referring to when I mentioned the weird behavior when parsing deployment outputs: #119

**Comment by t-dedah** [comment]
Hi @adrianmo @AshleyRoll we have released a new version so this should work fine now. Let me know if you are still facing this issue.

**Comment by AshleyRoll** [comment]
@t-dedah Awesome, thanks for the release.

I have re-run one of our pipelines that was previously warning about both `set-output` and the node.js version and I can confirm that both issues have been resolved. 

I think this issue can be closed now.
