### ISSUE TITLE
Skipping `Parsing Ouputs...` during arm-deploy step

### ISSUE THREAD

**Issue by rahul-fadv** [Azure/arm-deploy#119]
The `arm-deploy` action skips **Parsing Ouputs..** during the step execution. The outputs are populated in the Azure deployments. When we enabled logs to the runner, we could see the output object is pointing to a **null** value. 

Note: The `arm-deploy` step is part of a reusable workflow and the same workflow works for other bicep deployments

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/101121604/201664241-1d0fc7c2-7fa6-404b-b730-90da81590862.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/101121604/201664314-e403bb00-c697-4199-9faa-a5589cfcc889.png)

**Comment by adrianmo** [comment]
@rahul-fadv can you try if using `azure/arm-deploy@main` fixes your issue?

**Comment by t-dedah** [comment]
Sorry for the delay, we have released a new version so`@v1` now contains all the changes from `main`

**Comment by t-dedah** [comment]
Hi @adrianmo @rahul-fadv  we have released a new version so this should work fine now. Let me know if you are still facing this issue.
