### ISSUE TITLE
Mistake in readme

### ISSUE THREAD

**Issue by JorenFabre** [Azure/arm-deploy#121]
I noticed that you removed the `Required` tag from the `scope` parameter. Tho according to your action.yml this is a required parameter and there is no default to it.

**Comment by t-dedah** [comment]
Hi @JorenFabre thank you for the feedback. Scope is not `required` as its already being handled [here](https://github.com/Azure/arm-deploy/blob/main/src/main.ts#L15) so we will take the required steps to avoid any such confusion in the future.
