### ISSUE TITLE
deploying fileService fails with HTTP 400 after a fileservice has been created with "XML specified is not syntactically valid" during the EndRequest event

### ISSUE THREAD

**Issue by sydseter** [Azure/arm-deploy#124]
Hi,

The deployment seems to create all the resources, but still fails for the EndRequest when a filService is being created.

I am using a self-hosted github action runner with an official ubuntu focal image.

The template was generated by the azure portal. I just removed some of the circular dependencies to get it working.

Could this issue be due to incompatible Azure cli version?

arm-deploy: v1
Azure cli: (2.0.x) https://packages.ubuntu.com/source/focal/azure-cli 

Azure cli Message:

`ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidXmlDocument\",\r\n    \"message\": \"XML specified is not syntactically valid.\\nRequestId:159c9e46-901a-0021-729b-1b5b5f000000\\nTime:2022-12-29T15:39:40.9681373Z\"\r\n  }\r\n}"}]}}`

Azure activity logs:

https://gist.github.com/sydseter/3e6b28becdec123bfd80cb956dd9c7d3

Github action workflow yml:

https://gist.github.com/sydseter/6ffc4f027852ca9e7fe32add6cf37de4 

arm template.json:

https://gist.github.com/sydseter/3f27eb01f0cc6bd7287073f9a299912c

arm parameters.json:

https://gist.github.com/sydseter/b87f0d1135af5e21f9557737680b1988

**Comment by t-dedah** [comment]
Hi @sydseter This looks like an issue with the template provided. One of the suggested solutions is to remove the following properties from fileservice in the tempate. [Source](https://learn.microsoft.com/en-us/answers/questions/340510/arm-templates-storageaccountsfileservices-error-34.html)

```
"protocolSettings": {
      "smb": {}
  },
  "cors": {
      "corsRules": []
  },
```

**Comment by sydseter** [comment]
Great. Thank you very much. Resolved!!
