### ISSUE TITLE
Please add support for 'tenant' scoped deployments

### ISSUE THREAD

**Issue by bogdan-grozoiu** [Azure/arm-deploy#128]
Please allow users to perform tenant deployments, similar to 'New-AzTenantDeployment'.
Current scopes: managementGroup, subscription, resourceGroup (tenant is missing).

**Comment by rdeveen** [comment]
This is available in Release v2.0.
This PR is merged: https://github.com/Azure/arm-deploy/pull/125

**Comment by anthony-c-martin** [comment]
Closing this issue. Thanks @bearmannl for fixing this!
