### ISSUE TITLE
Override parameters for bicep parameter files

### ISSUE THREAD

**Issue by Jarod1662** [Azure/arm-deploy#139]
I'm in the process of creating workflows to deploy bicep & bicepparam files and need to pass some overrides however when doing so the overrides are not being set when the workflow is running.

![image](https://github.com/Azure/arm-deploy/assets/35074371/35a44bbb-500b-4c8c-857e-6a4a42ac50ae)
![image](https://github.com/Azure/arm-deploy/assets/35074371/48873520-57a8-4868-9dd6-1e8c4c07b984)

Workflow error:
![image](https://github.com/Azure/arm-deploy/assets/35074371/7fa229cc-b193-4c62-a5e0-cc78e3c61bb9)

I have tested using an ARM template and parameter file and this appears to be working as expected.
![image](https://github.com/Azure/arm-deploy/assets/35074371/2c660151-ec07-4d36-8d43-3b259b77cadd)
![image](https://github.com/Azure/arm-deploy/assets/35074371/c28c357b-df0f-4843-bd0f-1d4b52500069)

Any idea on how to resolve this issue?

**Comment by Jarod1662** [comment]
Ok appears to of been an issue on my side. I have resolved it.

**Comment by dandreasen-uncomn** [comment]
I am also seeing this issue using Bicep and bicepparam files and would like to give this a +1.

At this point, the resolution for me was to deploy the Bicep template along with a JSON ARM parameter file instead of a bicepparam file.

**Comment by Jarod1662** [comment]
@bishal-pdMSFT @t-dedah - any update on this?

**Comment by rdeveen** [comment]
This is not possible (yet) because bicepparam doesn't support it. See: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files?tabs=Bicep#parameter-precedence

**Comment by frasermclean** [comment]
Just wanted to add my +1 to this. I am experiencing this issue on my project. When running the `az deployment` locally, you can provide multiple `--parameters` options to override parameter values specified in the bicepparam file. So it should be possible to get this action working correctly,

**Comment by frasermclean** [comment]
As a workaround, you could trying running a `az bicep build-params --file yourfile.bicepparam` to create a JSON parameters file dynamically on the Actions runner. Then use that JSON file and override the parameters.

**Comment by jtomkiew-mng** [comment]
Regarding workarounds, can confirm the action **does not** override `bicepparam` parameters if defined in `parameters` input, e.g.:
```yaml
parameters: >-
  main.bicepparam
  customParameter=overrideValue
```

but it **does** work if specified in `additionalArguments` input, e.g.:
```yaml
parameters: main.bicepparam
additionalArguments: >-
  -p customParameter=overrideValue
```

**Comment by anthony-c-martin** [comment]
I believe this should be fixed by https://github.com/Azure/azure-cli/pull/28826.
