### ISSUE TITLE
bicepconfig.json linter settings ignored

### ISSUE THREAD

**Issue by thekie** [Azure/arm-deploy#141]
I am using a `bicepconfig.json` to set the linter level for `use-parent-property` to `info` to not have my pipeline fail because of one warning I currently can not get around. 

Deploying locally, I can see that the waning is silenced, but my GitHub Workflow fails because there is output on stderr.

Is there a way to use the `bicepconfig.json` with `arm-deploy` and getting around this without setting `failOnStdErr` to `false`?

**Comment by anthony-c-martin** [comment]
See the discussion under #126 - I would actually just recommend setting `failOnStdErr` to `false`.
