### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by gabrielweyer** [Azure/arm-deploy#153]
A warning is displayed when using the Action:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/login@v1, azure/arm-deploy@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by Jarod1662** [comment]
@anthony-c-martin @bearmannl - any news on when we can expect a new version to be released?

**Comment by anthony-c-martin** [comment]
I've just released [v2](https://github.com/Azure/arm-deploy/releases/tag/v2)
