### ISSUE TITLE
Feature Request - Create the Resource Group if it does not exist.

### ISSUE THREAD

**Issue by AmitSheth** [Azure/arm-deploy#17]
For a resource group scoped deployment (incremental mode), the resource group should be created if it does not exist.

**Comment by jdelforno** [comment]
As an optional flag only, it makes sense.

RGs are usually linked to RBAC, Monitoring and SIEM tools. Pretty sure Azure Policies can prevent the creation of resource groups as well, which would get in the way.

**Comment by bishal-pdMSFT** [comment]
> As an optional flag only, it makes sense.
> 
> RGs are usually linked to RBAC, Monitoring and SIEM tools. Pretty sure Azure Policies can prevent the creation of resource groups as well, which would get in the way.

For resource group scope deployments, a resource group is a necessity. We can skip creating if it already exists, but otherwise no harm in trying always.

**Comment by jdelforno** [comment]
> 
> 
> > As an optional flag only, it makes sense.
> > RGs are usually linked to RBAC, Monitoring and SIEM tools. Pretty sure Azure Policies can prevent the creation of resource groups as well, which would get in the way.
> 
> @jdelforno For resource group scope deployments, a resource group is a necessity. We can skip creating if it already exists, but otherwise no harm in trying always.

The only way to know if it already exists though, is if the service principle performing the deployment has access to check against all subscriptions and resource groups, which in a lot of cases, it will not.

Wouldn't this lead to duplicate resource groups being created?

**Comment by kanika1894** [comment]
Thank you for your feedback. This is now added to our backlog.
