### ISSUE TITLE
Allow for parameter override

### ISSUE THREAD

**Issue by vermegi** [Azure/arm-deploy#21]
When creating an ARM deployment, I would like to provide both a parameter file and override certain parameters through the arm-deploy action. This is handy when overall parameters exist in the parameter file, but you would like to override certain values during deploy in your pipeline. 

One example is where I want to use this action twice, once for creating a resource group, where I determine the resourcegroup name in the workflow and then reuse that value for deploying the resources. 

      # Deployment of resource group template    
      - name: Deploy ARM Template resourcegroup
        uses: azure/arm-deploy@v1
        with:
          # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: centralus # Set this to your target region
          template: repo/ARM/azuredeploy.resourcegroup.json  # Set this to the location of your template file
          parameters: repo/ARM/azuredeploy.resourcegroup.parameters.json # Set this to the location of your parameters file
          parameters: rgName=${{env.RESOURCEGROUP_NAME}} #override rgName in parameters file

      # Deployment of template    
      - name: Deploy ARM Template resources
        uses: azure/arm-deploy@v1
        with:
          # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourcegroup: ${{env.RESOURCEGROUP_NAME}} # reuse resourcegroup name
          region: centralus # Set this to your target region
          template: repo/ARM/azuredeploy.json  # Set this to the location of your template file
          parameters: repo/ARM/azuredeploy.parameters.json # Set this to the location of your parameters file

**Comment by kanika1894** [comment]
Hey @vermegi ,
You can override the parameters in parameter file by explictly calling it out next to the parameter file. 
Example :
``` parameters: repo/ARM/azuredeploy.resourcegroup.parameters.json  rgName=${{env.RESOURCEGROUP_NAME}} ```
This will override the rgName.

**Comment by vermegi** [comment]
Ah, excellent, didn't know that was possible. Can this be explicitly mentioned in the documentation/samples? It is not clear at the moment that this is also an option.

**Comment by kanika1894** [comment]
sure! @pulkitaggarwl can you please take care of the documentation?

**Comment by kanika1894** [comment]
https://github.com/Azure/arm-deploy/pull/26/files : changes merged
