### ISSUE TITLE
Validate Fails

### ISSUE THREAD

**Issue by marvinbuss** [Azure/arm-deploy#23]
When only validating templates I get the following error:

```sh
Validating template...
Warning: InvalidArgumentValueError: az deployment group validate: 'validate' is not a valid value for '--mode'.
Still stuck? Run 'az deployment group validate --help' to view all commands or go to 'https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest' to learn more

Warning: Template validation failed.
Creating deployment...
Warning: InvalidArgumentValueError: az deployment group create: 'validate' is not a valid value for '--mode'.
Try this: 'az deployment group create --resource-group testrg --name rollout01 --template-file azuredeploy.json --parameters '*** \"policyName\": *** \"value\": \"policy2\" *** ***''
Still stuck? Run 'az deployment group create --help' to view all commands or go to 'https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest' to learn more

Error: The process '/usr/bin/az' failed with exit code 2
```

**Comment by kanika1894** [comment]
Hey @marvinbuss 
Can you please share the input parameters that you used to run the action?
A screenshot can also work.

**Comment by marvinbuss** [comment]
@kanika1894 Sorry for my late reply. Here is the workflow: https://github.com/marvinbuss/mlflow-on-azure/actions/runs/364966556/workflow

**Comment by kanika1894** [comment]
@marvinbuss Thanks for sharing the logs. Looking into it and will get back to you.

**Comment by kanika1894** [comment]
Hey @marvinbuss, 
Instead of azure/arm-deploy@v1, can you try using azure/arm-deploy@v1.0.1 ?

**Comment by kanika1894** [comment]
Now it should work with azure/arm-deploy@v1 as well. There was some issue in tagging the release version.
Please check and let me know how it goes. :)

**Comment by marvinbuss** [comment]
This works now. Thank you!
