### ISSUE TITLE
Deployment fails if output section is defined in ARM template

### ISSUE THREAD

**Issue by upadhyayap** [Azure/arm-deploy#27]
### Issue
We have an ARM template where we are creating App insight and cosmos db resource, once resources are created, in output section we are trying to fetch the connection strings for the cosmos db as well as app insights key but this results in failure of deployment.
Deployment fails when output section is defined in the ARM template file. Please find the [sample repo](https://github.com/Devopsstarterms/nodeplainkubedb3-anupadh) where it is happening. It specifically fails on parsing output with below error.

```
Error: (e || "").replace is not a function
```

Please checkout this [action](https://github.com/Devopsstarterms/nodeplainkubedb3-anupadh/runs/1497471653?check_suite_focus=true) for more detailed error message

- ARM template is validated on portal and it is getting deployed successfully.

**Comment by upadhyayap** [comment]
@kanika1894 if you are right person, could you please look into it on priority.

**Comment by kanika1894** [comment]
Hey @upadhyayap 
can you please try running the workflow in debug mode?

**Comment by kanika1894** [comment]
@upadhyayap were you able to proceed?

**Comment by kanika1894** [comment]
As discussed with @upadhyayap, closing this for now until he faces some issue again.
