### ISSUE TITLE
Support for User Managed Identity

### ISSUE THREAD

**Issue by bahramr** [Azure/arm-deploy#29]
In order to prevent the possible exposure of credentials in the Cloud, we need to use a User Managed Identity to run this action from a self-hosted agent deployed in Azure.
Is there a plan to implement that?

**Comment by kanika1894** [comment]
Hey @bahramr, is this in terms of credentials that are used as parameters to run the action?
We can use secret store as a best practice.

**Comment by bahramr** [comment]
Hi @kanika1894 , this is to use the User Managed Identity object ID as a parameter of the AZ Login action. That way you don't have to store any secret in the cloud.

**Comment by kanika1894** [comment]
@pulkitaggarwl some insights on this?

**Comment by N-Usha** [comment]
Thanks @bahramr. MSI support is on our backlog. We are tracking it here: https://github.com/Azure/login/issues/56

**Comment by kanika1894** [comment]
As mentioned by @N-Usha , it's in backlog. So, closing this.
