### ISSUE TITLE
ResourceGroupLocation in example is incorrect format with spacing

### ISSUE THREAD

**Issue by thomast1906** [Azure/arm-deploy#37]
`ResourceGroupLocation: "Australia East"` errors with 

`ERROR: unrecognized arguments: East`

Correct reference

`ResourceGroupLocation: "AustraliaEast"`

**Comment by t-dedah** [comment]
Thanks for the observation @thomast1906 . PR raised for the solution. https://github.com/Azure/arm-deploy/pull/45

**Comment by t-dedah** [comment]
Thanks @thomast1906 for noticing. As PR for this has been merged so closing this issue.
