### ISSUE TITLE
stdout should be provided on deployment and validation

### ISSUE THREAD

**Issue by jontreynes** [Azure/arm-deploy#41]
When using arm-deploy @v1, there is no output of the validate or deployment steps - only these messages. 

![image](https://user-images.githubusercontent.com/19974635/116485468-4948de00-a859-11eb-9bc0-ecdc71b431f6.png)

To validate the deployment or validation steps, it would be nice to know the general deployment output by just writing the output from the `-o json` to standard output.

This will also help with history keeping when looking back at the logs.

**Comment by t-dedah** [comment]
Closing this Issues due to inactivity.
