### ISSUE TITLE
Is there any way to mark outputs of the template as secrets?

### ISSUE THREAD

**Issue by ashmind** [Azure/arm-deploy#47]
Looking at the code (https://github.com/Azure/arm-deploy/blob/main/src/utils/utils.ts), it seems that template outputs are always set using `setOutput`. However that means that all outputs are potentially visible in logs when used later.

For some more sensitive values (e.g. even AppInsights Instrumentation Key), it would be good to mask them in the logs.
This can be achieved by calling `core.setSecret` before `core.setOutput`.

This cannot be done _after_ `arm-deploy` (see https://github.com/actions/runner/issues/475), so it would be good if `arm-deploy` step could be configured to mark some outputs as secrets.

**Comment by marvinbuss** [comment]
@ashmind  You should not use secrets as outputs. These will also appear in the portal in the deployments section. This is generally not considered as good practice.

**Comment by ashmind** [comment]
Thanks! In that case it makes sense not to implement this.
