### ISSUE TITLE
Deploying bicep files with warnings fails the deployment

### ISSUE THREAD

**Issue by damienpontifex** [Azure/arm-deploy#59]
Using the task with a bicep file as the template parameter when bicep has warning outputs results in the message:

> Deployment process failed as some lines were written to stderr

This is correct, bicep is writing lines to stderr, but they are warnings only, not errors. 

The result is that the bicep deploy doesn't occur. If I use `az deployment sub create` locally, the bicep deployment completes successfully.

Is there a way to continue deployment even though these warnings are written to stderr? 

I've tried setting `continue-on-error: true` but it seems the error occurs after bicep to arm compilation and before the arm deployment so the result of this setting doesn't effect the ARM stage of the deployment

_I've opened an issue at https://github.com/Azure/bicep/issues/2905 for the underlying issue as the warnings are incorrect compared to the ARM spec._

**Comment by t-dedah** [comment]
Hi @damienpontifex , at the moment if stderr is not empty we throw an error. Considering stderr should only be used for errors, changing the behaviour will require a lot of approvals and changes.
Let's wait for the bicep team to come up with a fix then we can see if such a feature is needed or not.

**Comment by damienpontifex** [comment]
Thanks for the insight. I know they're also introducing listing and others, so warnings are probably a standard thing the bicep tool will continue to produce.
I'll raise it on the bicep repo as well with this info about warnings and stderr and it's relation to tasks such as this deployment and see where the discussion goes to get a good outcome

**Comment by bishal-pdMSFT** [comment]
Agree that this is a bicep issue and they should not put warnings in stderr.
We could introduce an input called failOnStdErr which can be set to false in such cases.

**Comment by alex-frankel** [comment]
Per this stackoverflow post, my understanding is the correct convention is to emit warnings to stderr:
https://stackoverflow.com/questions/1430956/should-i-output-warnings-to-stderr-or-stdout

Can the task instead read the error code of the command? If it is anything other than 0, the task should fail. cc @anthony-c-martin.

**Comment by bishal-pdMSFT** [comment]
Hi @damienpontifex/ @alex-frankel , there certainly seems to differing [opinions](https://unix.stackexchange.com/a/331831) in the community!

But yes, irrespective how different people think, it certainly seems over aggressive to fail the action if just a warning is written to stderr. Problem is that we do not know what is warning and what is an error. And we have seen customer complaints where a tool failed and just outputted to stderr without setting a non zero exit code.

What we can do is to introduce an input called `fail on standard error` which if set to false will ignore any data in stderr. the default value, though, will remain true to ensure backward compatible behavior.
Does this sound okay to you?

**Comment by alex-frankel** [comment]
>And we have seen customer complaints where a tool failed and just outputted to stderr without setting a non zero exit code.

I'd argue this is a bug in the tool, which should have emitted a non-zero exit code. My understanding is this the exact purpose of an exit code, so I'd strongly recommend we rely standard exit code patterns as the default behavior, with an option to opt-**in** to fail a task if there is any output on stderr like you are describing.

>What we can do is to introduce an input called fail on standard error which if set to false will ignore any data in stderr. 

How will this task work with error codes in this case? Let's say I've opted in to this new property such that the task will *not* fail if there is output on stderr, will the task now respect error codes?  

> the default value, though, will remain true to ensure backward compatible behavior.

Instead of keeping the current default behavior, which I think leads to unexpected results, can we instead introduce a new default behavior in a new version of the task? i.e. `azure/arm-deploy@2` It would be good to take advantage of semantic versioning for these types of things.

Thoughts?

**Comment by bishal-pdMSFT** [comment]
> How will this task work with error codes in this case? Let's say I've opted in to this new property such that the task will not fail if there is output on stderr, will the task now respect error codes?

Yes, it should always respect exit code.

**Comment by bishal-pdMSFT** [comment]
> Instead of keeping the current default behavior, which I think leads to unexpected results, can we instead introduce a new default behavior in a new version of the task? i.e. azure/arm-deploy@2 It would be good to take advantage of semantic versioning for these types of things.

Yes, this is a good candidate for v2. We will add this to backlog for v2.

**Comment by t-dedah** [comment]
@damienpontifex We are working on the fix for this issue [here](https://github.com/Azure/arm-deploy/pull/61).

**Comment by damienpontifex** [comment]
Thanks @t-dedah I've been following that PR as well and keen to try out the fix once merged. 
Thanks for the open discussion on this and jumping straight in to figure something out

**Comment by damienpontifex** [comment]
I have tried my deployment again using `azure/arm-deploy@releases/v1` with the setting `failOnStdErr: false` and everything worked as expected.

Thank you for the open discussion and quick turnaround 🎉. I'd be happy to close (maybe you'll want to wait until v1 tag is updated to include this change)

**Comment by t-dedah** [comment]
@damienpontifex We have released the fix in v1, now you can test that too.

**Comment by damienpontifex** [comment]
I switched it back to `azure/arm-deploy@v1` and got the original error "deployment process failed as some lines were written to stderr"

Maybe caching of the task or something. I'll give it a day and queue it again to try again because I can see https://github.com/Azure/arm-deploy/tree/v1 has the commit merged in already.

**Comment by t-dedah** [comment]
@damienpontifex , let me check.

**Comment by t-dedah** [comment]
@damienpontifex Please try again, there was issue with build process but its resolved now.

**Comment by damienpontifex** [comment]
@t-dedah tried again and it worked with `@v1` 🍾

**Comment by t-dedah** [comment]
@damienpontifex I am closing this issue now, feel free to reopen if you have any more queries.
