### ISSUE TITLE
Connection string parameter from repo secret error

### ISSUE THREAD

**Issue by dalmasj** [Azure/arm-deploy#68]
Hi there,

I try to deploy azure datafctory with multiple parameters including connection string of sql server.
I have this following issue when trying tu set connection string (store in a GitHub secret) to a parameter:
![image](https://user-images.githubusercontent.com/83807850/125082881-05c7e700-e0c8-11eb-859b-92083f681a64.png)
I think it's because the connection string contains white space ("[...]intial catalog=[...]")

With quotes(simple and double) i have this error :
![image](https://user-images.githubusercontent.com/83807850/125083285-766f0380-e0c8-11eb-91a0-3cdd0902a444.png)
In the ARM template the parameter is a "SecureString"

**Comment by andrewwiebe** [comment]
I am trying to do something similar, I have all of my parameters in a json file passed to the deployment. Is there anyway to append the one secret from a Github secret to the deployment?

**Comment by dpetrishin** [comment]
Any update or workaround about this problem, guys?...

**Comment by dpetrishin** [comment]
I solved this by wrapping of parameters in "".

**Comment by t-dedah** [comment]
Closing this issue as a working solution was suggested @dpetrishin. Feel free to reopen if you face this issue again.
