### ISSUE TITLE
Add deployment mode "WhatIf"

### ISSUE THREAD

**Issue by marvinbuss** [Azure/arm-deploy#71]
It would be great, if you could add a what-if deployment mode to understand changes that will be made before merging the changes into main. Please let me know, if you have more questions about the feature request.

For more details: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-what-if?tabs=azure-powershell

**Comment by t-dedah** [comment]
Hi @marvinbuss 
Can you please explain what use case this mode will solve? We looked into it and it made more sense while being used in a CLI where you see changes and confirm whether we want to go ahead with deployment or not. 

Also how urgent is this feature?

**Comment by marvinbuss** [comment]
Hi @t-dedah,
The idea is to use this in a PR to check what changes will be made once the PR gets merged back into the `main` branch. I don't need this feature tomorrow, but it would be nice to get this implemented.

**Comment by t-dedah** [comment]
Thanks @marvinbuss for the insight. We will keep you posted on this feature request.

**Comment by larryclaman** [comment]
I agree with @marvinbuss 's use case.  A similar use case would be in a CICD deployment scenario using [approval workflows](https://devblogs.microsoft.com/devops/i-need-manual-approvers-for-github-actions-and-i-got-them-now/), where you would 'pause' after the what-if action ran so that an operator could say Yes/No to proceeding with the deployment.
Conceptually, this would be very similar to how Terraform does their plan / apply workflow.

**Comment by marvinbuss** [comment]
@t-dedah Any updates?

**Comment by t-dedah** [comment]
Hi @marvinbuss I will be picking this up in next sprint, hope that wont be an issue.

**Comment by marvinbuss** [comment]
Next sprint should be fine. Once this is included, I will add this to our CI/CD pipelines and test the feature.

**Comment by marvinbuss** [comment]
Hi @t-dedah,
Any updates on this? Thanks!

**Comment by t-dedah** [comment]
Hi @marvinbuss its WIP, will be raising PR soon.

**Comment by larryclaman** [comment]
#not-stale

**Comment by larryclaman** [comment]
#not-stale

**Comment by t-dedah** [comment]
@larryclaman @marvinbuss @johndowns We have released a new version with support for `additional additionalArguments`.

All the extra parameters can be passed as string using additionalArguments.

`additionalArguments: "--what-if --what-if-exclude-change-types Create Ignore"`

**Comment by marvinbuss** [comment]
Hi @t-dedah,
What do I need to do to specify a what-if deployment. This is failing:
https://github.com/Azure/data-product-streaming/blob/01b8b3c72e2d3d2fb8c3d1402ecf035f518f9062/.github/workflows/dataProductDeployment.yml#L63-L75

Thanks for your help!

**Comment by marvinbuss** [comment]
I don't really understand why it is modelled as additional parameter, since it is is actually a [deployment mode within Azure CLI](https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest#az_deployment_group_what_if).

But there is no what-if branch in the deployment options here: https://github.com/Azure/arm-deploy/blob/main/src/deploy/scope_resourcegroup.ts

**Comment by t-dedah** [comment]
Hi @marvinbuss 
As `what-if` is already a parameter in az group create, we decided to use that in order to reuse the current code. All the functionalities are still same but now with addition of `additionalArguments` there will be no further need of enhancements through separate input for each of new request.

https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest#az_deployment_group_create

**Comment by marvinbuss** [comment]
Thanks for the prompt response @t-dedah! 🚀 
I have tested the new feature and it works as expected. Thanks for this!
Here is the yaml: https://github.com/Azure/data-product-streaming/blob/b10ff6bd2ab9112f7605305a54b52917dec058d8/.github/workflows/dataProductDeployment.yml#L62-L75

And here is a successful run of the workflow: https://github.com/Azure/data-product-streaming/runs/4309573044?check_suite_focus=true

**Comment by marvinbuss** [comment]
@t-dedah The output could be improved. There are some warnings that should be removed:
![image](https://user-images.githubusercontent.com/34542414/143212185-52d6e4c6-6e54-49ad-b802-00ee5e530c57.png)

**Comment by nnellans** [comment]
Agree about cleaning up the output.  I don't want to see errors like that when doing a "what-if" deployment.

**Comment by t-dedah** [comment]
We have removed the `additionalArguments` while validation step. This should resolve the warnings and other related issues.

**Comment by t-dedah** [comment]
Please reopen the issue if needed.

**Comment by nnellans** [comment]
I'm seeing an issue now where my additional arguments are getting added to my template filename:

`Error: ERROR: [Errno 2] No such file or directory: 'test.bicep--what-if'`

**Comment by marvinbuss** [comment]
@t-dedah Please reopen this issue. I am running into the same error.

**Comment by t-dedah** [comment]
@marvinbuss @nnellans We have released a new version with the fix for this bug.

**Comment by larryclaman** [comment]
> As `what-if` is already a parameter in az group create, we decided to use that in order to reuse the current code. All the functionalities are still same but now with addition of `additionalArguments` there will be no further need of enhancements through separate input for each of new request.

@t-dedah , would it be possible to update the main README to mention that _what-if_ can be passed via additionalArguments?  I'm finding that users are not aware of this feature.

**Comment by t-dedah** [comment]
Hi @larryclaman sorry for the delay. Will this be enough or should we add more details?
PR - https://github.com/Azure/arm-deploy/pull/102
