### ISSUE TITLE
README.md overly complex

### ISSUE THREAD

**Issue by larryclaman** [Azure/arm-deploy#76]
While reviewing the README file, the example for "Another example which ensures the Azure Resource Group exists before ARM deployment" seems overly complex.  Currently the code example shows:
```
        inlineScript: |
          #!/bin/bash
          if $(az group exists --name ${{ env.ResourceGroupName }}) ; then
            echo "Azure resource group already exists, skipping creation..."
          else
            az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"
          fi
```

`az group create` is an idempotent command (it returns success even if the group already exists), so I don't think the conditional code is necessary at all. I believe you could simply run:
```
          #!/bin/bash
            az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"
```

I realize this is a nitpick but simplicity should always be valued :)

**Comment by t-dedah** [comment]
@larryclaman Not sure if it is important but if we try to create new resource with same name in different location then the command returns an error 
`(InvalidResourceGroupLocation) Invalid resource group location 'eastus'. The Resource group already exists in location 'westus'.`

**Comment by larryclaman** [comment]
interesting... thanks for pointing that out; was not aware of this failure scenario.
