### ISSUE TITLE
Redeploying Bastion via template fails (Subnet AzureBastionSubnet is in use)

### ISSUE THREAD

**Issue by nielsvdc** [Azure/arm-deploy#80]
I'm not sure if this belongs here, but I'll give it a try.

I've created a bicep template to deploy a vnet resource with a Bastion resource. The first time deploying this template works as expected and all resources are created.

But when redeploying the template, I get the error _"Subnet AzureBastionSubnet is in use by /subscriptions/..../resourceGroups/rg-test/providers/Microsoft.Network/bastionHosts/avd-vnet-bastion/bastionHostIp
Configurations/IpConf and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet."_

What I'm expecting is that when redeploying the template, it would detected that the resources exist and no changes are made to the resources. This is how other templates work when deploying other resources. I don't understand why it's trying to delete the AzureBastionSubnet.

See attached file that is the bicep template.
[bastion.txt](https://github.com/Azure/arm-deploy/files/7065996/bastion.txt)

**Comment by marvinbuss** [comment]
@nielsvdc This is related to this behavior stated here: https://stackoverflow.com/questions/55901747/azure-arm-code-inusesubnetcannotbedeleted-when-trying-to-update-vnet

When the vnet gets deployed and no subnets are specified in the properties section, the vnet tries to delete the subnets. However, services are connected and hence, the deployment fails. Just the first deployment works fine, as there is no subnet that is in use.

**Comment by nielsvdc** [comment]
Sorry people, I was unavailable for a moment. I tested with redeployment with CLI and also via Azure GUI. These also both failed with error message "Subnet AzureBastionSubnet is in use by /subscriptions/.../resourceGroups/test/providers/Microsoft.Network/bastionHosts/avd-vnet-bastion-eus/bastionHostIpConfigurations/IpConf and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet."

**Comment by t-dedah** [comment]
Hi @nielsvdc, if we try to run `az deployment group what-if ...` we get the below outcome which clearly shows that they are trying to delete IpConf. So this looks like an expected behaviour. 

This is a possibility when different resources doesnt have context about other resources as explained in this [article]( https://stackoverflow.com/questions/55901747/azure-arm-code-inusesubnetcannotbedeleted-when-trying-to-update-vnet)

If you still feel this should not be an expected behaviour then as we use azure-cli internally yo make these calls, they will be able to help you out. Can you please raise an issue here? https://github.com/Azure/azure-cli

```
Note: The result may contain false positive predictions (noise).
You can help us improve the accuracy of the result by opening an issue here: https://aka.ms/WhatIfIssues.

Resource and property changes are indicated with these symbols:
  - Delete
  ~ Modify
  = Nochange
  * Ignore

The deployment will update the following scope:

Scope: /subscriptions/c00d16c7-6c1f-4c03-9be1-6934a4c49682/resourceGroups/deepak-rg

  ~ Microsoft.Network/bastionHosts/avd-vnet-bastion [2021-02-01]
    - properties.dnsName:    "bst-fffc8494-9771-467e-979f-389868569805.bastion.azure.com"
    - properties.scaleUnits: 2
    ~ properties.ipConfigurations: [
      ~ 0:

        - id: "/subscriptions/c00d16c7-6c1f-4c03-9be1-6934a4c49682/resourceGroups/deepak-rg/providers/Microsoft.Network/bastionHosts/avd-vnet-bastion/bastionHostIpConfigurations/IpConf"

      ]
    ~ sku.name:              "Basic" => "Standard"

  ~ Microsoft.Network/publicIPAddresses/avd-vnet-bastion-ip [2021-02-01]
    - sku.tier: "Regional"

  = Microsoft.Network/virtualNetworks/myVnet [2021-02-01]
  = Microsoft.Network/virtualNetworks/myVnet/subnets/AzureBastionSubnet [2021-02-01]
  * Microsoft.Network/networkSecurityGroups/NRMS-mqpdnhjdzis7mmyVnet
  * Microsoft.Network/networkSecurityGroups/NRMS-wlg2nxyjuzp7ymyVnet-AzureBastionSubnet
  * Microsoft.Storage/storageAccounts/deepak21
  * Microsoft.Storage/storageAccounts/deepak2121
  * Microsoft.Storage/storageAccounts/devstore4z32rb65cghuc
  * Microsoft.Web/serverFarms/AppServicePlan-GEN-UNIQUE
  * Microsoft.Web/serverFarms/devplan
  * Microsoft.Web/sites/devapp4z32rb65cghuc

Resource changes: 2 to modify, 2 no change, 8 to ignore.
```

**Comment by t-dedah** [comment]
Hi @nielsvdc are you still facing this issue? If no, then should we close this?
