### ISSUE TITLE
Provide support for overrideParameters

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/arm-deploy#83]
Provide support for overrideParameters allowing you to combine parameter files with overrides per environment similar to https://github.com/marketplace/actions/azure-resource-manager-arm-template-deployment.

This is useful if you rely on parameter files, but for some scenarios you want to deviate from what is in the file.

**Comment by andrewwiebe** [comment]
I Just want to add a +1 to this. This would be very very useful to "inject" GitHub secrets into a deployment.

**Comment by marvinbuss** [comment]
This is already possible. Just look at the closed issues: https://github.com/Azure/arm-deploy/issues/21

Here is a sample: https://github.com/Azure/data-product-analytics/blob/fb9830eaf04dd2449f4d173200533653b45cf881/.github/workflows/dataProductDeployment.yml#L98-L110

**Comment by tomkerkhove** [comment]
Oh, then I'd suggest to update the README - Are you open for PRs?

**Comment by t-dedah** [comment]
Hi @tomkerkhove We are open to PRs and any other suggestions to the README.
