### ISSUE TITLE
Pass github secret to the template being deployed

### ISSUE THREAD

**Issue by andrewwiebe** [Azure/arm-deploy#85]
Is there anyway to pass a git hub repo secret to the arm template being deployed? Would like to pass a secret to an app service to be used during deployment.

**Comment by marvinbuss** [comment]
Please look at this issue. You can override secrets the same way: https://github.com/Azure/arm-deploy/issues/21

You can also find an example here: 
https://github.com/Azure/data-product-analytics/blob/fb9830eaf04dd2449f4d173200533653b45cf881/.github/workflows/dataProductDeployment.yml#L98-L110

**Comment by andrewwiebe** [comment]
Awesome thanks for the link and example. Might be good to add to the readme.

**Comment by bahramr** [comment]
I tried this with a bicep parameter file and for some reasons the parameters are not overridden when using secrets, such as this example

name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: "rg-contoso"
          template: ./main.bicep
          parameters: ./main.parameters.bicepparam adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }}
          failOnStdErr: false
