### ISSUE TITLE
Support `--rollback-on-error` option

### ISSUE THREAD

**Issue by danwkennedy** [Azure/arm-deploy#89]
The Az CLI (and Az Powershell module) have a method of specifying the behavior of the deployment should an error happen during the run. In this case, we can either specify a deployment name to rollback to or simply use it as a flag to rollback to the latest successful deployment if there's an error. It'd be great if this parameter was exposed to the GH Action.

**Comment by t-dedah** [comment]
@danwkennedy Added this enhancement with what-if PR  https://github.com/Azure/arm-deploy/pull/90

**Comment by t-dedah** [comment]
@danwkennedy We have released a new version with support for `additional additionalArguments`.

All the extra parameters can be passed as string using additionalArguments.

`additionalArguments: "--rollback-on-error"`

**Comment by t-dedah** [comment]
Closing this issue as this was fixed last week. Please reopen if you have more questions on the new input.

**Comment by danwkennedy** [comment]
@t-dedah thanks for getting that out!
